name: Rust
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          name: [linux, windows]
          #name: [linux, windows, macos]

          include:
            - name: linux
              os: ubuntu-latest
            - name: windows
              os: windows-latest
            #- name: macos
            #  os: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check formatting      
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test --all-features